import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
phx_host = System.get_env("PHX_HOST") || "shipmyapp.in"
other_host1 = System.get_env("OTHER_HOST1") || "shipmyapp.in"
other_host2 = System.get_env("OTHER_HOST2") || "shipmyapp.in"

config :chax, ChaxWeb.Endpoint,
  url: [host: phx_host, port: 443, scheme: "https"],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  check_origin: [phx_host, other_host1, other_host2],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Chax.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
